### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by Eimuex** [giansalex/binance-stoploss#1]
Is it possible to get a short installation manual? If I run image from docker hub (giansalex/binance-stoploss) container won't start. Also, how to execute bot commands if I make it work?  Thank you

My command:
```
docker run -d --name stoploss \
-e BINANCE_APIKEY=my key \
-e BINANCE_SECRET=my secret \
giansalex/binance-stoploss:latest
```

**Comment by giansalex** [comment]
Example:
```bash
docker run -d --name binance_sell_dot \
-e BINANCE_APIKEY=xxxxxx \
-e BINANCE_SECRET=xxxxxx \
-e TELEGRAM_TOKEN=xxxx:xxxxxx \
giansalex/binance-stoploss:latest \
-type=SELL -pair=DOT/USDT -percent=2 -interval=60 -amount=4.99 -telegram.chat=XXXXX
```

I use [portainer](https://www.portainer.io/) as container admin.
![image](https://user-images.githubusercontent.com/14926587/93491065-e0ff4a80-f8ce-11ea-8d9e-a6a3bfbe96ac.png)

telegram notifications:
![image](https://user-images.githubusercontent.com/14926587/93490874-a5fd1700-f8ce-11ea-820b-65081a288fb7.png)

**Comment by Eimuex** [comment]
Working like a charm, thank you very much.
