### ISSUE TITLE
Cancel limit orders before market sell

### ISSUE THREAD

**Issue by Eimuex** [giansalex/binance-stoploss#3]
I would like to edit code to cancel all active orders before executing market sell. Could I get a small hint since I’m not a programmer? Thank you

**Comment by Eimuex** [comment]
Found this  code, seems relevant to me

```
// CancelOrder cancels order.
func (b *binance) CancelOrder(cor CancelOrderRequest) (*CanceledOrder, error) {
	return b.Service.CancelOrder(cor)
}
```
```
canceledOrder, err := b.CancelOrder(binance.CancelOrderRequest{
    Symbol:    "BNBETH",
    OrderID:   newOrder.OrderID,
    Timestamp: time.Now(),
})
if err != nil {
    panic(err)
}
fmt.Printf("%#v\n", canceledOrder)
```

**Comment by giansalex** [comment]
@Eimuex this repo use [go-binance](https://github.com/adshao/go-binance) package
you need to [list open orders](https://github.com/adshao/go-binance#list-open-orders) and then [cancel orders](https://github.com/adshao/go-binance#cancel-order).

> If you're not developer, this is very complicated.

**Comment by Eimuex** [comment]
Thanks!
