### ISSUE TITLE
<APIError> code=-1013, msg=Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by Eimuex** [giansalex/binance-stoploss#4]
`Cannot create sell order, error:<APIError> code=-1013, msg=Filter failure: LOT_SIZE`

I got this error when script reached stop loss price. Had enough funds though. Same thing on couple of pairs.

**Comment by giansalex** [comment]
I found this [same error](https://stackoverflow.com/a/62753685).
> This error appears because you are trying to create an order with a quantity lower than the minimun required.

**Comment by Eimuex** [comment]
Thanks for all these fast responses, really appreciate it. 

Found something similar online, but I had far more then minimum amount and was able to sell manually on site. 

Didn’t use ‘-amount’ parameter cause I wanted 100% sell, now I tried with specified amount and sell went without problems. Amount was 3x smaller than the previous one. 

I’m thinking maybe fees could be the problem? Had no BNB balance and when it tries to sell 100% it fails?

**Comment by Eimuex** [comment]
Not sure that I understand everything but [this thread](https://github.com/sammchardy/python-binance/issues/219) might be useful. Could be that decimal problem? I'm trading USDT pairs if that's relevant.

**Comment by giansalex** [comment]
Yes, i believe that.

**Comment by giansalex** [comment]
Balance api, always return 8 decimals.
![image](https://user-images.githubusercontent.com/14926587/95349912-30f57f80-0885-11eb-8282-d3e892462918.png)

**Comment by giansalex** [comment]
You should use `-amount` flag 😕

**Comment by Eimuex** [comment]
`Quantity(round(quantity, 6)` instead of `Quantity(quantity)` wouldn't work?

**Comment by giansalex** [comment]
This example with 6 decimales, (but depend if coin is `BTC`, `XRP`, etc).

Add `fmt` to import:
```go
import (
    	"fmt"
)
```

And `Sell` method.
```go

// Sell create a sell order to market price
func (exchange *Binance) Sell(market string, quantity string) (string, error) {
	quantityVal, _ := strconv.ParseFloat(quantity, 64)
	quantity = fmt.Sprintf("%.6f", quantityVal) //  6 decimals
	
	order, err := exchange.api.NewCreateOrderService().Symbol(market).
		Side(binance.SideTypeSell).Type(binance.OrderTypeMarket).
		Quantity(quantity).Do(exchange.ctx)

	if err != nil {
		return "", err
	}

	return strconv.FormatInt(order.OrderID, 10), nil
}
```

**Comment by Eimuex** [comment]
No luck this time, same error. I'll keep trying so leaving this issue open.

**Comment by giansalex** [comment]
Which coin?

**Comment by Eimuex** [comment]
ADA/USDT, FLM/USDT, BNB/USDT tried those 3

**Comment by giansalex** [comment]
For `ADA/USDT`, decimals: 1
![image](https://user-images.githubusercontent.com/14926587/95387337-33240200-08b6-11eb-863d-61c5ab8703d5.png)

BNB/USDT - decimals: 3

**Comment by Eimuex** [comment]
Oh I get it now. Tried with 3 (changed "%.6f" to "%.3f" and re-compiled) but again same thing.
